### ISSUE TITLE
Small typo on documentation AWS Signature v4 documentation

### ISSUE THREAD

**Issue by huima** [grafana/k6-jslib-aws#103]
On page: https://grafana.com/docs/k6/latest/javascript-api/jslib/aws/signaturev4/

The  Signature v4 option object descriptions on credentials part lists 'secretAccessKeyId' even though code uses secretAccessKey.

**Comment by oleiade** [comment]
Hey @huima 👋🏻 

Thanks a lot for pointing this out, you're correct, we'll address that as soon as possible 🤝
