### ISSUE TITLE
Type error with latest `@types/k6` version

### ISSUE THREAD

**Issue by fullheart** [grafana/k6-jslib-aws#115]
**Problem**: The TS file `src/internal/s3.ts` has a type error with the latest `@types/k6` package.

Version
- **k6-jslib-aws** `v0.12.3`
- **@types/k6** `~0.52.0`

Error message:
```sh
src/internal/s3.ts:200:13 - error TS2345: Argument of type 'string | ArrayBuffer' is not assignable to parameter of type 'string | bytes'.
  Type 'ArrayBuffer' is not assignable to type 'string | bytes'.
    Type 'ArrayBuffer' is missing the following properties from type 'number[]': length, pop, push, concat, and 28 more.

200             res.body
                ~~~~~~~~


Found 1 error in src/internal/s3.ts:200
```

How to reproduce?
```sh
git clone git@github.com:grafana/k6-jslib-aws.git
cd k6-jslib-aws/
git checkout v0.12.3
npm install --save-dev @types/k6 # Install latest `@types/k6` package
npx tsc -t es5 src/internal/s3.ts # See error output above
```

**Comment by mstoykov** [comment]
This has been fixed in the current master in b312325

cc @oleiade are we going to be releasing a version soon?

**Comment by oleiade** [comment]
I'll be making a release as soon as possible indeed 🙇🏻

**Comment by oleiade** [comment]
[jslib-aws v0.13.0](https://github.com/grafana/k6-jslib-aws/releases/tag/v0.13.0) is out. @fullheart would you mind trying again and let us know if it addressed your issue 👍🏻 

Without a sign back from you I'll close this issue in a week 🙇🏻

**Comment by fullheart** [comment]
@oleiade Great, thanks. I tested version 0.13.0. The type error is fixed. I am closing the issue.
