### ISSUE TITLE
Example contains AWS secrets

### ISSUE THREAD

**Issue by QAInsights** [grafana/k6-jslib-aws#2]
This test contains the AWS secrets, is this dummy ones or real? Please check. Thanks.

https://github.com/grafana/k6-jslib-aws/blob/main/tests/internal/signature.js

**Comment by oleiade** [comment]
Hi @QAInsights,

Thanks for reaching out 🙇🏻 ! No worries, those secrets are not real ones, they're precomputed ones we have put together ourselves for the test 👍🏻
