### ISSUE TITLE
Using k6-jslib-aws

### ISSUE THREAD

**Issue by jayush12** [grafana/k6-jslib-aws#23]
Hi Is it possible to use this library to upload or download files on Minio (hosted at our own server). As per examples I am not able to see any way to use minio.

**Comment by oleiade** [comment]
Hi @jayush12 

I'm not familiar with Minio. Do you mean [this min.io](https://min.io/)?
This jslib is specifically designed to interact with AWS S3. I haven't tried to use it with a different storage backend, but I assume that if said storage backend exposes an S3 compatible, it might be compatible. No guarantees though 👍🏻

**Comment by imiric** [comment]
@oleiade Yes, that Minio. Technically, there's no reason the current `S3Client` shouldn't work with any S3-compatible API, like Minio and Ceph. It should just be a matter of exposing the URL to connect to.

I see that there's a recent PR #21 that adds support for Ceph, and the author mentions it might work for Minio as well. @jayush12 Can you test with [@ismaelpuerto's fork](https://github.com/ismaelpuerto/k6-jslib-aws) and let us know if it works for you? It should be a matter of specifying `rgw: true` and `endpoint: "<minio URL>"` in the `AWSConfig` object, if I'm understanding the code correctly. Though we should ask to make this implementation generic and not specific to Ceph RGW, and that some documentation is added.

**Comment by oleiade** [comment]
@jayush12 we have published `v0.7.0.` which supports setting the `host` of our client classes. This might be helpful in your case as it will allow you to [point the SDK to your min.io instance](https://github.com/grafana/k6-jslib-aws/blob/main/tests/internal/s3.js#L6). We do not intend to support min.io officially as of now, thus I'll close this issue, but feel free to open a new one with concrete issues you might run into and we'll do our best to support you 🙇🏻
