### ISSUE TITLE
Add support for DynamoDB

### ISSUE THREAD

**Issue by james4388** [grafana/k6-jslib-aws#39]
I have a working dynamodb client. If you found it useful I can make an MR. I used it for clean up stuff created by load test or prepare data for test?

**Comment by oleiade** [comment]
Hey @james4388 

We welcome every contribution, and I'm sure that if you found it useful enough to implement it, other users will too 🤞🏻 
Thus, feel free to open a PR if you have the bandwidth for it. We'll make sure to review and provide support toward merging it 👍🏻
