### ISSUE TITLE
Support for SQS doesn't seem to work

### ISSUE THREAD

**Issue by elelha** [grafana/k6-jslib-aws#40]
I'm trying to use the SQS client in my k6 load test as described in the [docs](https://github.com/grafana/k6-jslib-aws#sqs) but the test fails with this error:
`Remote resolution error: "not found: https://jslib.k6.io/aws/0.7.1/sqs.js"`
Screenshot:
![Screenshot 2023-04-19 at 1 38 37 PM](https://user-images.githubusercontent.com/32271955/233156001-f5df6ff0-9025-4132-b29c-9aaef787ab74.png)

The link to the dedicated k6 documentation page is also broken in the [docs](https://github.com/grafana/k6-jslib-aws#sqs). 
![Screenshot 2023-04-19 at 1 41 47 PM](https://user-images.githubusercontent.com/32271955/233156631-eda7e19c-9bcb-495e-86a2-c1f153c0572f.png)

Is the sqs jslib still supported?

Snippet of the sqs jslib implementation:
![Screenshot 2023-04-19 at 1 44 08 PM](https://user-images.githubusercontent.com/32271955/233157175-e5a3ebb6-3f89-4a99-a08d-c40df0805678.png)
^ I've tried 0.7.0 and 0.7.1.
I'm currently using k6 0.36.0.

**Comment by oleiade** [comment]
Hi @elelha 👋🏻 

Sorry for the mishap. The documentation for SQS made it to the website before we got a chance to produce a new release of the jslib containing it indeed. 

I'm on it, and will let you know when it's published 👍

**Comment by oleiade** [comment]
Hey @elelha 

A quick heads up that we have release version `0.7.2` which includes SQS support. You should be able to import it as usual using the following URL: `https://jslib.k6.io/aws/0.7.2/sqs.js`.

Can confirm that it addresses your issue? 🙇🏻

**Comment by elelha** [comment]
Yes, it does! Thanks for the quick resolution 🎉

**Comment by oleiade** [comment]
Perfect, glad I could help 🙇🏻
