### ISSUE TITLE
Modify Protocol from Hardcoded 'https' to Dynamic Scheme

### ISSUE THREAD

**Issue by NPJigaK** [grafana/k6-jslib-aws#49]
https://github.com/grafana/k6-jslib-aws/blob/main/src/internal/sqs.ts#L70
https://github.com/grafana/k6-jslib-aws/blob/main/src/internal/sqs.ts#L133

When calling the SQSClient methods, the protocol is currently hardcoded to `https` in the `signature.sign`. 
Could you please change this to `protocol: this.scheme`?
Thank you in advance.

**Comment by mstoykov** [comment]
Hi @NPJigaK, thanks for reporting this.

This seems reasonable - can you please make the change and test it locally that it fixes the problem you are having. 

This way we can be certain that we won't just make a change and it will not have the desired effect.

You can then also open a pull request to be merged in the repo :)

**Comment by NPJigaK** [comment]
Yes, I installed k6-jslib-aws locally and made this modification to check the scenario in localstack. And I have confirmed that it works correctly.

I could not create a pull request because this repository does not have write permissions.

**Comment by mstoykov** [comment]
@NPJigaK you can fork and create a pull request from your fork to this repo

You can see the documentation about [Creating a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) and the linked [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
