### ISSUE TITLE
SQSClient.sendMessage method doesn't support sending message attributes

### ISSUE THREAD

**Issue by viggu888** [grafana/k6-jslib-aws#66]
I am only able to send the message body using [SQSClient.sendMessage](https://k6.io/docs/javascript-api/jslib/aws/sqsclient/sqsclient-sendmessage/) and not able to send any message attributes. Kindly address this issue.

**Comment by oleiade** [comment]
Hi @viggu888 👋🏻 

#65 should provide what you're looking for.

As a general note, this is an open-source project, and whenever in need for a specific feature, please feel free to open a pull request for it, and we will gladly support you to bring it to the finish line 🙇🏻

**Comment by viggu888** [comment]
yeah thanks. it works now.
